name: Build e testes
on: [push, pull_request]
jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build src/Target.Desafio/Target.Desafio.csproj --configuration Release
      - run: dotnet test tests/Target.Desafio.Tests/Target.Desafio.Tests.csproj --configuration Release
